@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "6538afae85c60bfd9941b2fa",
  "receiverId": "6538afab85c60bfd9941b2f0",
  "receiverName":"Daniel",
  "body": "siemkaa dupa",
  "isRead": false
}

###
POST {{baseUrl}}/{{urlPath}}/chat/settings
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "startTime": "00:00",
  "endTime": "23:59",
  "startDay": "Monday",
  "endDay": "Friday"
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/settings/65803e3babea24ffcae6bc6c
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "startTime": "6:00",
  "endTime": "20:00",
  "startDay": "Friday",
  "endDay": "Sunday"
}


###
GET {{baseUrl}}/{{urlPath}}/chat/settings/list
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/chat/message/user/65378617266082a84cfdb5d3
Content-Type: application/json
Accept: application/json
withCredentials: true

###
DELETE {{baseUrl}}/{{urlPath}}/chat/message/656778497ba8d0fd7b53745d/656778467ba8d0fd7b537454
# For this endpoint, the type is either deleteForMe or deleteForEveryone
Content-Type: application/json
Accept: application/json
withCredentials: true

###
DELETE {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/64973f781ae3018138b2e165/deleteForEveryone
# For this endpoint, the type is either deleteForMe or deleteForEveryone
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/mark-as-read
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "senderId": "64956dfb84dc705b5ad08cc8",
  "receiverId": "64187c79b173a91849641026"
}

