@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/client
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "eventId": "64946cbd6d76d9cbbd0af87e",
  "eventName": "Zakopane 2023",
  "name": "Gucio Hujecki",
  "email": "skur@wp.pl",
  "tel": "602456456",
  "birthDate": "2023-06-06",
  "price": "1000"
}

###
GET {{baseUrl}}/{{urlPath}}/client/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/client/64955924893a2455d4e39ee8
Content-Type: application/json
Accept: application/json
withCredentials: true


###
DELETE {{baseUrl}}/{{urlPath}}/client/6495543ec38a2df6ec470f4c
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/client/6495543ec38a2df6ec470f4c
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "eventId": "64946cbd6d76d9cbbd0af87e",
  "eventName": "Zakopane 2023",
  "name": "Gucio Duppa",
  "email": "skur@wp.pl",
  "tel": "602456456",
  "birthDate": "2023-06-06",
  "price": "1000"
}
